### PR TITLE
Installation for OSX Catalina Working--

### PR DESCRIPTION
**Pull request by iamh2o**
I figured out how to get around a handful of bugs with the current WDT OSX codebase (contributed those to WDT), and tweaked this fork so I could write an OSX warp-cli install script (which I need more mac testers for, but it worked on my 2 laptops).

Minimal changes were made to warp, removed a few hard coded paths that don't play well with Mac's and removed the folly version reporting as one of the WDT fixes meant going to system folly.

I just sent a bunch of data around.  I hope some OSX folks find this useful :-)

jem

### CODE REVIEW

**Comment by JustinTimperio** [comment]
Hi @iamh2o, 

First off thanks for the push. This is very helpful since I have no Mac to test on. I just have a few questions about the code. 

1. What is the point of `warp_optimized.py` over `warp.py`?
2. I assume hardcoded paths are broke on Mac? I gave full paths to avoid [path-hijacking](https://medium.com/r3d-buck3t/hijacking-relative-paths-in-suid-programs-fed804694e6e)
3. Can you explain the file limit issue? That is not an issue i have observed on Linux so far.

**Comment by iamh2o** [comment]
1) Oh - oops, I didn't realize the optimized had been added.  That can be discarded, it was setup for a very weird, very fussy old ubuntu 16 box(ARM too).

2) I eliminated the hardcoded paths b/c they are different on OSX, and due to a strange sys admin, different on our old ubuntu 16 server.
I was not familiar with path hijacking.... I guess detecting paths with which is not better.  Perhaps a cli config setting that can be over-ridden?

3) Oh-  the file limit issue.  I had vague WDT crashes totally unclear.  I finally hit a lucky search for the line of code and the crash, and lo-and-behold, it was simply ulimit.  This was ubuntu 20-18, one of the boxes had low default settings by the sysadmin.... i was sending something like 90,000 files.  The limit there is actually probably too high, I had to tone it down one order of magnitude to work on the ubuntu 16 box.

**Comment by JustinTimperio** [comment]
Okay just remove the unused file and I will merge this.

**Comment by iamh2o** [comment]
hi-- sorry my time for fun coding evaporated for a few weeks.  Thanks for chopping out that file.  I hope this is useful to some folks!

jem

**Pull request merged**
